# Generated by Django 5.0.6 on 2024-05-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-date', '-votes']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
